#!/bin/bash
YFParray=( Ypet )
RecogDomainarray=( FHA2 FHA1EV )
Phosphoarray=( T507 S296 )
CFParray=( Aquamarine mCerulean3 mTurquoise2 mT2_206A mT2_206A_208F mT2_206A_208F_224L )
LocalisationSignalarray=( NLS )

if [ -e "FRET folder" ]; then
    echo "Already exists! Aborting..."
    exit 1
fi

mkdir "FRET folder"
cd "FRET folder"
currentPath=$(pwd)

for localsignal in ${LocalisationSignalarray[@]}; do
    for acceptor in ${YFParray[@]}; do
        for recogdomain in ${RecogDomainarray[@]}; do
            cd "$currentPath"
            mkdir "$recogdomain"
            cd "$recogdomain"
            currentRecog=$(pwd)
            for phosphosite in ${Phosphoarray[@]}; do
                cd "$currentRecog"
                mkdir "$recogdomain-$phosphosite"
                cd "$recogdomain-$phosphosite"
                for donor in ${CFParray[@]}; do
                    mkdir "$acceptor-$recogdomain-$phosphosite-$donor-$localsignal"
                done
            done
        done
    done
done
