#!/bin/bash
YFParray=( Ypet )
RecogDomainarray=( FHA2 FHA1EV )
Phosphoarray=( T507 S296 )
CFParray=( Aquamarine mCerulean3 mTurquoise2 mT2_206A mT2_206A_208F mT2_206A_208F_224L )
LocalisationSignalarray=( NLS )

for localsignal in ${LocalisationSignalarray[@]}; do
    for acceptor in ${YFParray[@]}; do
        for recogdomain in ${RecogDomainarray[@]}; do
            for phosphosite in ${Phosphoarray[@]}; do
                for donor in ${CFParray[@]}; do
                    echo "> $acceptor-$recogdomain-$phosphosite-$donor-$localsignal"
                    echo "> Concentration?"
                    read currentConcentration
                    dilution=$(echo "scale=2; 500/$currentConcentration" | bc -l)
                    echo "> $acceptor-$recogdomain-$phosphosite-$donor-$localsignal"
                    echo "> $currentConcentration ng/uL => $dilution uL"
                    echo "($acceptor-$recogdomain-$phosphosite-$donor-$localsignal) $currentConcentration ng/uL => $dilution uL" >> FRETdilution.txt
                    echo
                done
            done
        done
    done
done
